
//接受主线程的数据请求
addEventListener("message",function(e){
    if(e.data=="请求数据"){
        let arr=[
            {
                "title":"格香客(平安店)加载",
                "price":"人均￥25",
                "time":"35",
                "img":"1.jpg"
            },{
                "title":"自助小火锅加载",
                "price":"人均￥15",
                "time":"55",
                "img":"3.jpg"
            },
            {
                "title":"小龙虾加载",
                "price":"人均￥56",
                "time":"39",
                "img":"2.jpg"
            },{
                "title":"兰州拉面加载",
                "price":"人均￥10",
                "time":"25",
                "img":"1.jpg"
            },{
                "title":"肯德基(北园店)加载",
                "price":"人均￥65",
                "time":"5",
                "img":"3.jpg"
            },{
                "title":"南京小笼包加载",
                "price":"人均￥12",
                "time":"42",
                "img":"1.jpg"
            },{
                "title":"盖浇饭加载",
                "price":"人均￥14",
                "time":"21",
                "img":"2.jpg"
            },{
                "title":"驴肉火烧加载",
                "price":"人均￥18",
                "time":"50",
                "img":"1.jpg"
            }
        ]

        //三秒钟后像主线程发送数据
        setTimeout(function(){
            postMessage(arr)
        },Math.random()*4000)
    }
})