require.config({
    paths:{
        'swiper':'./app/libs/swiper.min',
        'index':'./app/js/index',
        'mySwiper':'./app/js/mySwiper',
        'Skip':'./app/js/skip',
        'render':'./app/js/render',
        'jquery':'./app/libs/jquery.min',
        "addr":'./app/js/addr',
        'localStorage':'./app/js/localStorage'
    }
})